# Generated by Django 4.1.5 on 2023-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('stateRow', models.CharField(auto_created='A', max_length=1, verbose_name='Nombre')),
                ('idIngrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nameIngrediente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unidad', models.CharField(max_length=100, verbose_name='UnidadMedida')),
                ('cantMP', models.IntegerField()),
            ],
        ),
    ]
