# Generated by Django 4.1.5 on 2023-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente', '0002_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='stateRow',
            field=models.CharField(default='A', max_length=1, verbose_name='EstadoFila'),
        ),
    ]
